services:
  - type: web
    name: my-web-service
    env: node
    plan: free
    repo: https://github.com/Yoploo/render-bp-test
    buildCommand: npm install && npm run build
    startCommand: npm start
    staticPublishPath: public
    autoDeploy: true
    regions:
      - frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
            name: my-database
            property: connectionString

databases:
    - name: my-database
      plan: free
      region: frankfurt